language: node_js
os:
  - osx
  - linux
script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      npm run test-mac64
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      npm run test-linux64
    fi
